---

- name: install redis server
  sudo: true
  apt:
    pkg=redis-server
    state=present

- name: add redis configuration file
  sudo: true
  template:
    src=redis.conf.j2
    dest=/etc/redis/redis.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart the redis daemon

- name: start redis and enable it on boot
  sudo: true
  service:
    name=redis-server
    state=started
    enabled=yes
