---

- name: download the nodejs archive
  become: true
  get_url:
    url=https://nodejs.org/download/release/v4.3.2/node-v4.3.2-linux-x64.tar.gz
    dest=/tmp/node-v4.3.2-linux-x64.tar.gz
    owner=root
    group=root
    mode=0644

- name: extract the nodejs binaries
  become: true
  command:
    tar -C /usr/local --strip-components 1 -xzf /tmp/node-v4.3.2-linux-x64.tar.gz

- name: install lambda-related packages
  become: true
  npm:
    name={{ item}}
    global=yes
  with_items:
    - serverless
    - aws-sdk
